// Generated by scripts/sync-meta.mjs from zinmin232/advui@v0.6.0. Do not edit by hand:
// run `pnpm sync-meta` after upgrading @advui/core.
import type { ComponentMeta } from './advuiMetaTypes'

/** The @advui/core version these snapshots were taken from. */
export const advuiMetaVersion = '0.6.0'

export const buttonMeta: ComponentMeta = {
  name: 'Button',
  slug: 'button',
  category: 'buttons',
  description: 'Triggers an action or event, such as submitting a form or opening a dialog.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Button', 'ButtonText', 'ButtonFrame', 'ButtonContext'],
  keywords: ['action', 'submit', 'cta', 'click', 'press'],
  parts: [
    {
      name: 'Button',
      props: [
        {
          name: 'variant',
          type: "'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link'",
          default: "'default'",
          description: 'Visual style. Use one `default` button per view for the primary action.',
        },
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg' | 'icon'",
          default: "'md'",
          description: 'Height and padding.',
        },
        {
          name: 'loading',
          type: 'boolean',
          default: 'false',
          description: 'Shows a spinner, sets `aria-busy` and blocks presses.',
        },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Disables interaction and removes it from the tab order.',
        },
        {
          name: 'icon',
          type: 'ReactNode',
          description: 'Icon before the label. Inherits size and color.',
        },
        { name: 'iconAfter', type: 'ReactNode', description: 'Icon after the label.' },
        {
          name: 'fullWidth',
          type: 'boolean',
          default: 'false',
          description: 'Stretch to the container width.',
        },
        {
          name: 'onPress',
          type: '(event) => void',
          description: 'Called on click, tap, Enter or Space.',
        },
        {
          name: 'render',
          type: "'button' | 'a' | ReactElement",
          default: "'button'",
          description: 'Render as a different element, e.g. `<a href>` for links.',
        },
      ],
    },
    {
      name: 'Button.Text',
      description: 'Styled label for custom compositions. Plain string children are wrapped automatically.',
      props: [],
    },
  ],
  examples: [
    { name: 'basic', title: 'Basic' },
    {
      name: 'variants',
      title: 'Variants',
      description: 'Six variants for different levels of emphasis.',
    },
    { name: 'sizes', title: 'Sizes' },
    { name: 'with-icon', title: 'With icon' },
    {
      name: 'loading',
      title: 'Loading',
      description: 'Keeps its width, announces busy state and ignores presses.',
    },
    { name: 'disabled', title: 'Disabled' },
    {
      name: 'full-width',
      title: 'Full width (mobile)',
      description: 'Common for primary actions on small screens.',
    },
  ],
  playground: {
    component: 'Button',
    children: 'Get started',
    controls: [
      {
        prop: 'variant',
        type: 'select',
        options: ['default', 'secondary', 'outline', 'ghost', 'destructive', 'link'],
        default: 'default',
      },
      { prop: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md' },
      { prop: 'disabled', type: 'boolean', default: false },
      { prop: 'loading', type: 'boolean', default: false },
      { prop: 'fullWidth', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'Hover and press states use CSS; `render={<a href="/pricing" />}` turns it into a link.',
    ios: 'Pressable area is extended with `hitSlop` to meet the 44pt minimum touch target.',
    android: 'Same touch-target extension as iOS (48dp recommended; use `lg` for primary actions). With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['icon-button', 'button-group', 'toggle'],
}

export const cardMeta: ComponentMeta = {
  name: 'Card',
  slug: 'card',
  category: 'data-display',
  description: 'A surface that groups related content and actions.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Card'],
  keywords: ['panel', 'surface', 'container', 'tile'],
  parts: [
    {
      name: 'Card',
      props: [
        {
          name: 'variant',
          type: "'outline' | 'elevated' | 'filled' | 'ghost'",
          default: "'outline'",
          description: 'Surface style.',
        },
        {
          name: 'interactive',
          type: 'boolean',
          default: 'false',
          description: 'Hover/press feedback and focus ring. Add `onPress` + `role`/label.',
        },
      ],
    },
    { name: 'Card.Header', description: 'Vertical stack with title and description.', props: [] },
    { name: 'Card.Title', description: 'Heading text (`role="heading"`).', props: [] },
    { name: 'Card.Description', description: 'Muted supporting text.', props: [] },
    { name: 'Card.Content', description: 'Main body with consistent padding.', props: [] },
    { name: 'Card.Footer', description: 'Row for actions.', props: [] },
  ],
  examples: [
    { name: 'basic', title: 'Form card' },
    { name: 'variants', title: 'Variants' },
    { name: 'interactive', title: 'Interactive' },
  ],
  playground: {
    component: 'Card',
    controls: [
      {
        prop: 'variant',
        type: 'select',
        options: ['outline', 'elevated', 'filled', 'ghost'],
        default: 'outline',
      },
      { prop: 'interactive', type: 'boolean', default: false },
    ],
  },
  related: ['separator', 'button'],
}

export const inputMeta: ComponentMeta = {
  name: 'Input',
  slug: 'input',
  category: 'forms',
  description: 'A single-line text field.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Input', 'inputBaseStyle', 'fieldBoxStyle'],
  keywords: ['text field', 'textbox', 'form', 'email', 'password'],
  parts: [
    {
      name: 'Input',
      description: 'Accepts all Tamagui Input / TextInput props (value, onChangeText, secureTextEntry, …).',
      props: [
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg'",
          default: "'md'",
          description: '32, 40 or 48px tall.',
        },
        {
          name: 'invalid',
          type: 'boolean',
          default: 'false',
          description: 'Error styling + `aria-invalid`.',
        },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Prevents editing.' },
        {
          name: 'value / defaultValue',
          type: 'string',
          description: 'Controlled or uncontrolled value.',
        },
        {
          name: 'onChangeText',
          type: '(text: string) => void',
          description: 'Called on every change (web and native).',
        },
        {
          name: 'placeholder',
          type: 'string',
          description: 'Hint text — never a replacement for a label.',
        },
      ],
    },
  ],
  examples: [
    { name: 'basic', title: 'With label' },
    { name: 'sizes', title: 'Sizes' },
    { name: 'states', title: 'Invalid and disabled' },
  ],
  playground: {
    component: 'Input',
    staticProps: { 'aria-label': 'Email' },
    controls: [
      { prop: 'placeholder', type: 'text', default: 'you@example.com' },
      { prop: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md' },
      { prop: 'invalid', type: 'boolean', default: false },
      { prop: 'disabled', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'Renders a native `<input>`, so autofill and password managers work.',
    ios: 'Use `keyboardType`, `textContentType` and `autoComplete` for the right keyboard and autofill.',
    android: 'Use `keyboardType` and `autoComplete`; wrap forms in `KeyboardAvoidingView` on small screens.',
  },
  related: ['label', 'textarea', 'select'],
}

export const badgeMeta: ComponentMeta = {
  name: 'Badge',
  slug: 'badge',
  category: 'foundations',
  description: 'A small label for status, counts or categories.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Badge', 'BadgeText', 'BadgeFrame'],
  keywords: ['tag', 'chip', 'status', 'label', 'pill'],
  parts: [
    {
      name: 'Badge',
      props: [
        {
          name: 'variant',
          type: "'default' | 'secondary' | 'outline' | 'destructive' | 'success' | 'warning' | 'info'",
          default: "'default'",
          description: 'Color intent.',
        },
        { name: 'size', type: "'sm' | 'md'", default: "'md'", description: 'Padding scale.' },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon (12px, tinted to match).' },
      ],
    },
  ],
  examples: [{ name: 'variants', title: 'Variants' }, { name: 'with-icon', title: 'With icon' }],
  playground: {
    component: 'Badge',
    children: 'Badge',
    controls: [
      {
        prop: 'variant',
        type: 'select',
        options: ['default', 'secondary', 'outline', 'destructive', 'success', 'warning', 'info'],
        default: 'default',
      },
      { prop: 'size', type: 'select', options: ['sm', 'md'], default: 'md' },
    ],
  },
  related: ['avatar', 'alert'],
}

export const imageMeta: ComponentMeta = {
  name: 'Image',
  slug: 'image',
  category: 'media',
  description: 'A picture in a box of a set size or ratio, with a placeholder and a fallback.',
  status: 'beta',
  since: '0.6.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Image', 'ImageProps'],
  keywords: ['image', 'img', 'picture', 'photo', 'media', 'fallback', 'placeholder', 'object-fit'],
  parts: [
    {
      name: 'Image',
      description: 'Also takes View style props for the box (`width`, `height`, `borderRadius`…).',
      props: [
        {
          name: 'src',
          type: 'string | number',
          required: true,
          description: 'URL, or the result of `require()` for a bundled image on native.',
        },
        {
          name: 'alt',
          type: 'string',
          required: true,
          description: 'What the image shows. `""` for decoration.',
        },
        {
          name: 'ratio',
          type: 'number',
          description: 'Width divided by height. Without it, give the image a `height`.',
        },
        {
          name: 'fit',
          type: "'cover' | 'contain' | 'fill' | 'none' | 'scale-down'",
          default: "'cover'",
          description: 'How the picture fills the box (`object-fit` / `resizeMode`).',
        },
        {
          name: 'fallback',
          type: 'ReactNode',
          default: 'image icon',
          description: 'Shown when the image fails to load.',
        },
        {
          name: 'loading',
          type: "'lazy' | 'eager'",
          description: 'Web only: `lazy` waits until the image nears the viewport.',
        },
        { name: 'onLoad', type: '() => void', description: 'The image loaded.' },
        { name: 'onError', type: '() => void', description: 'The image failed to load.' },
      ],
    },
  ],
  examples: [
    { name: 'basic', title: 'Basic' },
    { name: 'fit', title: 'Cover and contain' },
    {
      name: 'fallback',
      title: 'Fallback',
      description: 'A missing file shows the default icon, or your own content.',
    },
  ],
  platformNotes: {
    web: 'Renders an `<img>` with `object-fit`. A load or error that happened before hydration is read from the element once mounted.',
    ios: 'Uses React Native’s `Image`; `fit` maps to `resizeMode`. Remote images need a size from the box (`ratio` or `height`).',
    android: 'Same as iOS. Use HTTPS URLs.',
  },
  related: ['aspect-ratio', 'avatar', 'skeleton'],
}

export const typographyMeta: ComponentMeta = {
  name: 'Typography',
  slug: 'typography',
  category: 'foundations',
  description: 'Text, Heading and Kbd components built on the type scale and semantic colors.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Text', 'Heading', 'Kbd'],
  keywords: ['text', 'heading', 'font', 'h1', 'paragraph', 'type scale'],
  parts: [
    {
      name: 'Text',
      props: [
        {
          name: 'size',
          type: "'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' … '6xl'",
          default: "'base'",
          description: '12px → 60px.',
        },
        {
          name: 'weight',
          type: "'normal' | 'medium' | 'semibold' | 'bold'",
          description: 'Font weight.',
        },
        {
          name: 'tone',
          type: "'default' | 'muted' | 'primary' | 'success' | 'warning' | 'error' | 'info' | 'inherit'",
          description: 'Semantic color.',
        },
        { name: 'truncate', type: 'boolean', description: 'Single line with ellipsis.' },
        { name: 'mono', type: 'boolean', description: 'Monospace font.' },
      ],
    },
    {
      name: 'Heading',
      props: [
        {
          name: 'level',
          type: '1 | 2 | 3 | 4 | 5 | 6',
          default: '2',
          description: 'Semantic level (h1–h6).',
        },
        {
          name: 'size',
          type: 'TextSize',
          description: 'Override the visual size independently of the level.',
        },
      ],
    },
    { name: 'Kbd', description: 'Keyboard key hint rendered as `<kbd>` on web.', props: [] },
  ],
  examples: [{ name: 'scale', title: 'Type scale' }, { name: 'tones', title: 'Tones' }],
  related: ['theme', 'colors'],
}

export const aspectRatioMeta: ComponentMeta = {
  name: 'Aspect Ratio',
  slug: 'aspect-ratio',
  category: 'layout',
  description: 'Keeps content at a fixed width-to-height ratio as the width changes, for images, video and maps.',
  status: 'beta',
  since: '0.3.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['AspectRatio'],
  keywords: ['ratio', '16:9', 'image', 'video', 'embed', 'responsive media'],
  parts: [
    {
      name: 'AspectRatio',
      props: [
        {
          name: 'ratio',
          type: 'number',
          default: '1',
          description: 'Width divided by height, e.g. `16 / 9`.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          description: 'Content that fills the box: 100% width and height, or absolutely positioned.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Image' }, { name: 'ratios', title: 'Common ratios' }],
  platformNotes: {
    web: 'Uses the CSS `aspect-ratio` property.',
    ios: 'Uses the React Native `aspectRatio` style.',
    android: 'Same as iOS.',
  },
  related: ['avatar', 'card'],
}

export const containerMeta: ComponentMeta = {
  name: 'Container',
  slug: 'container',
  category: 'layout',
  description: 'Centers page content with a max width and responsive side padding.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Container'],
  keywords: ['page', 'wrapper', 'max width', 'center'],
  parts: [
    {
      name: 'Container',
      props: [
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg' | 'xl' | 'full'",
          default: "'xl'",
          description: 'Max width (breakpoint widths).',
        },
      ],
    },
  ],
  examples: [{ name: 'container', title: 'Page container' }],
  related: ['stack', 'grid'],
}

export const gridMeta: ComponentMeta = {
  name: 'Grid',
  slug: 'grid',
  category: 'layout',
  description: 'Equal-width responsive columns that work identically on web and native.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Grid'],
  keywords: ['columns', 'grid', 'responsive', 'cards', 'gallery'],
  parts: [
    {
      name: 'Grid',
      props: [
        {
          name: 'columns',
          type: 'number | { base?, xs?, sm?, md?, lg?, xl?, xxl? }',
          default: '1',
          description: 'Column count, optionally per breakpoint (mobile-first).',
        },
        { name: 'gap', type: 'SpaceTokens', default: "'$4'", description: 'Gap between cells.' },
      ],
    },
  ],
  examples: [{ name: 'grid', title: 'Responsive stats' }],
  platformNotes: {
    web: 'Flex-wrap based (CSS grid is not available on native).',
    ios: 'Flex-wrap based.',
    android: 'Flex-wrap based.',
  },
  related: ['stack', 'container'],
}

export const scrollAreaMeta: ComponentMeta = {
  name: 'Scroll Area',
  slug: 'scroll-area',
  category: 'layout',
  description: 'A box that scrolls its content within a set height or width. On web its scrollbars are thin and in the theme colors.',
  status: 'beta',
  since: '0.3.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['ScrollArea'],
  keywords: ['scroll', 'overflow', 'scrollbar', 'list', 'carousel', 'scroll view'],
  parts: [
    {
      name: 'ScrollArea',
      description: 'Takes size and border props such as `height`, `maxWidth` and `borderRadius`.',
      props: [
        {
          name: 'orientation',
          type: "'vertical' | 'horizontal'",
          default: "'vertical'",
          description: 'Which way it scrolls.',
        },
        {
          name: 'aria-label',
          type: 'string',
          description: 'Names the region for screen readers. Recommended.',
        },
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          description: 'One child that holds the content, such as a VStack (an HStack when horizontal).',
        },
      ],
    },
  ],
  examples: [
    { name: 'basic', title: 'Vertical list' },
    { name: 'horizontal', title: 'Horizontal row' },
  ],
  platformNotes: {
    web: 'A scrolling box with CSS `scrollbar-width: thin` and theme colors (browsers without support show their default scrollbar).',
    ios: 'A ScrollView with the platform scroll indicator.',
    android: 'Same as iOS.',
  },
  related: ['sheet', 'separator'],
}

export const stackMeta: ComponentMeta = {
  name: 'Stack',
  slug: 'stack',
  category: 'layout',
  description: 'Flexbox primitives: Box, Stack, HStack, VStack, Center and Spacer.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Box', 'Stack', 'HStack', 'VStack', 'Center', 'Spacer'],
  keywords: [
    'flex',
    'row',
    'column',
    'box',
    'layout',
    'gap',
    'hstack',
    'vstack',
    'center',
    'spacer',
  ],
  parts: [
    { name: 'Box', description: 'A `View` with every style prop and token.', props: [] },
    {
      name: 'Stack',
      description: 'Flex column. Style it with standard props — no custom API to learn.',
      props: [
        {
          name: 'flexDirection',
          type: "'row' | 'column' | …",
          default: "'column'",
          description: 'Main axis.',
        },
        {
          name: 'alignItems / justifyContent',
          type: 'FlexAlign',
          description: 'Alignment (shorthands: `items`, `justify`).',
        },
        { name: 'gap', type: 'SpaceTokens', description: 'Space between children, e.g. `$2`.' },
        {
          name: '$sm / $md / $lg …',
          type: 'style object',
          description: 'Responsive overrides per breakpoint.',
        },
      ],
    },
    {
      name: 'HStack / VStack',
      description: 'Row (centered) / column presets of Stack.',
      props: [],
    },
    { name: 'Center / Spacer', description: 'Center children; push siblings apart.', props: [] },
  ],
  examples: [
    { name: 'basic', title: 'Stacks and spacer' },
    { name: 'responsive', title: 'Responsive direction' },
  ],
  related: ['grid', 'container'],
}

export const labelMeta: ComponentMeta = {
  name: 'Label',
  slug: 'label',
  category: 'forms',
  description: 'An accessible label linked to a form control.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Label'],
  keywords: ['form', 'caption', 'field name'],
  parts: [
    {
      name: 'Label',
      props: [
        { name: 'htmlFor', type: 'string', description: 'The `id` of the control it labels.' },
        {
          name: 'required',
          type: 'boolean',
          default: 'false',
          description: 'Shows a visual “*” (mark the input itself `required`).',
        },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Dims the label to match a disabled control.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Labelling controls' }],
  related: ['input', 'checkbox', 'switch'],
}

export const textareaMeta: ComponentMeta = {
  name: 'Textarea',
  slug: 'textarea',
  category: 'forms',
  description: 'A multi-line text field for longer input.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Textarea'],
  keywords: ['multiline', 'comment', 'message', 'bio'],
  parts: [
    {
      name: 'Textarea',
      props: [
        {
          name: 'invalid',
          type: 'boolean',
          default: 'false',
          description: 'Error styling + `aria-invalid`.',
        },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Prevents editing.' },
        {
          name: 'resize',
          type: "'none' | 'vertical'",
          default: "'vertical'",
          description: 'User resizing (web only).',
        },
        { name: 'rows', type: 'number', description: 'Initial visible lines (web).' },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'With label and hint' }],
  platformNotes: {
    web: 'Renders a native `<textarea>`.',
    ios: 'Multiline `TextInput`; text aligns to the top.',
    android: 'Multiline `TextInput` with `textAlignVertical="top"`.',
  },
  related: ['input', 'label'],
}

export const checkboxMeta: ComponentMeta = {
  name: 'Checkbox',
  slug: 'checkbox',
  category: 'forms',
  description: 'Lets users select one or more options, or toggle a single setting before submitting.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Checkbox'],
  keywords: ['check', 'tick', 'option', 'terms', 'indeterminate'],
  parts: [
    {
      name: 'Checkbox',
      props: [
        { name: 'checked', type: "boolean | 'indeterminate'", description: 'Controlled state.' },
        {
          name: 'defaultChecked',
          type: "boolean | 'indeterminate'",
          default: 'false',
          description: 'Initial state when uncontrolled.',
        },
        {
          name: 'onCheckedChange',
          type: "(checked: boolean | 'indeterminate') => void",
          description: 'Called when toggled.',
        },
        { name: 'size', type: "'sm' | 'md'", default: "'md'", description: '16 or 20px.' },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Prevents toggling.' },
        {
          name: 'invalid',
          type: 'boolean',
          default: 'false',
          description: 'Error styling + `aria-invalid`.',
        },
        {
          name: 'name / value / required',
          type: 'string / string / boolean',
          description: 'Native form participation (web).',
        },
      ],
    },
  ],
  examples: [
    { name: 'basic', title: 'With label' },
    { name: 'indeterminate', title: 'Indeterminate (select all)' },
  ],
  playground: {
    component: 'Checkbox',
    staticProps: { 'aria-label': 'Accept terms' },
    controls: [
      { prop: 'size', type: 'select', options: ['sm', 'md'], default: 'md' },
      { prop: 'defaultChecked', type: 'boolean', default: true },
      { prop: 'disabled', type: 'boolean', default: false },
      { prop: 'invalid', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'Custom-drawn control backed by a hidden `<input type="checkbox">`.',
    ios: 'Pressable with checkbox semantics (iOS has no native checkbox).',
    android: 'Pressable with checkbox semantics announced by TalkBack.',
  },
  related: ['switch', 'radio-group', 'label'],
}

export const switchMeta: ComponentMeta = {
  name: 'Switch',
  slug: 'switch',
  category: 'forms',
  description: 'An on/off toggle for settings that take effect immediately.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Switch'],
  keywords: ['toggle', 'on off', 'setting', 'preference'],
  parts: [
    {
      name: 'Switch',
      props: [
        {
          name: 'checked / defaultChecked',
          type: 'boolean',
          description: 'Controlled / uncontrolled state.',
        },
        {
          name: 'onCheckedChange',
          type: '(checked: boolean) => void',
          description: 'Called when toggled.',
        },
        { name: 'size', type: "'sm' | 'md'", default: "'md'", description: '36×20 or 44×24.' },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Prevents toggling.' },
      ],
    },
  ],
  examples: [{ name: 'settings', title: 'Settings list' }],
  playground: {
    component: 'Switch',
    staticProps: { 'aria-label': 'Airplane mode' },
    controls: [
      { prop: 'size', type: 'select', options: ['sm', 'md'], default: 'md' },
      { prop: 'defaultChecked', type: 'boolean', default: true },
      { prop: 'disabled', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'Rendered as a `<button role="switch">` with a hidden checkbox for forms.',
    ios: 'Custom drawn for visual consistency across platforms.',
    android: 'Custom drawn; TalkBack announces “switch, on/off”.',
  },
  related: ['checkbox', 'label'],
}

export const separatorMeta: ComponentMeta = {
  name: 'Separator',
  slug: 'separator',
  category: 'foundations',
  description: 'A thin line that divides content horizontally or vertically.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Separator'],
  keywords: ['divider', 'hr', 'rule', 'line'],
  parts: [
    {
      name: 'Separator',
      props: [
        {
          name: 'orientation',
          type: "'horizontal' | 'vertical'",
          default: "'horizontal'",
          description: 'Direction of the line.',
        },
        {
          name: 'decorative',
          type: 'boolean',
          default: 'true',
          description: 'When false, exposes `role="separator"` to assistive technology.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Horizontal and vertical' }],
  related: ['card'],
}

export const selectMeta: ComponentMeta = {
  name: 'Select',
  slug: 'select',
  category: 'forms',
  description: 'Choose one option from a list — a dropdown on desktop, a bottom sheet on touch devices.',
  status: 'beta',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Select'],
  keywords: ['dropdown', 'picker', 'listbox', 'combobox', 'options'],
  parts: [
    {
      name: 'Select',
      props: [
        { name: 'value / defaultValue', type: 'string', description: 'Selected value.' },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          description: 'Called with the chosen value.',
        },
        {
          name: 'placeholder',
          type: 'string',
          default: "'Select…'",
          description: 'Shown when nothing is selected.',
        },
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg'",
          default: "'md'",
          description: 'Trigger height.',
        },
        {
          name: 'invalid / disabled',
          type: 'boolean',
          description: 'Error styling / disable the trigger.',
        },
        {
          name: 'id / aria-label',
          type: 'string',
          description: 'Link to a Label, or name it directly.',
        },
        {
          name: 'width',
          type: 'SizeTokens | string',
          default: "'100%'",
          description: 'Trigger width.',
        },
      ],
    },
    {
      name: 'Select.Item',
      props: [
        {
          name: 'value',
          type: 'string',
          required: true,
          description: 'Option value. Children are the label.',
        },
      ],
    },
    {
      name: 'Select.Group',
      props: [{ name: 'label', type: 'string', description: 'Group heading.' }],
    },
  ],
  examples: [{ name: 'basic', title: 'Basic' }, { name: 'groups', title: 'Grouped options' }],
  platformNotes: {
    web: 'Server-renders a static trigger and mounts the interactive select after hydration (avoids SSR mismatches).',
    ios: 'Opens in a bottom sheet (Tamagui Sheet).',
    android: 'Opens in a bottom sheet; back button closes it. With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['radio-group', 'combobox'],
}

export const tabsMeta: ComponentMeta = {
  name: 'Tabs',
  slug: 'tabs',
  category: 'navigation',
  description: 'Switch between related panels of content within the same view.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Tabs'],
  keywords: ['tab bar', 'segmented', 'panels', 'sections'],
  parts: [
    {
      name: 'Tabs',
      props: [
        { name: 'value / defaultValue', type: 'string', description: 'Active tab.' },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          description: 'Called when the tab changes.',
        },
        {
          name: 'variant',
          type: "'pills' | 'underline'",
          default: "'pills'",
          description: 'Visual style.',
        },
        {
          name: 'orientation',
          type: "'horizontal' | 'vertical'",
          default: "'horizontal'",
          description: 'Arrow-key direction.',
        },
        {
          name: 'activationMode',
          type: "'automatic' | 'manual'",
          default: "'automatic'",
          description: 'Select on focus, or on Enter/Space.',
        },
      ],
    },
    {
      name: 'Tabs.List',
      props: [
        { name: 'loop', type: 'boolean', default: 'true', description: 'Wrap focus at the ends.' },
      ],
    },
    {
      name: 'Tabs.Trigger',
      props: [
        { name: 'value', type: 'string', required: true, description: 'Tab id.' },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon.' },
        { name: 'disabled', type: 'boolean', description: 'Skip this tab.' },
      ],
    },
    {
      name: 'Tabs.Content',
      props: [{ name: 'value', type: 'string', required: true, description: 'Matching tab id.' }],
    },
  ],
  examples: [
    { name: 'basic', title: 'Pills' },
    { name: 'underline', title: 'Underline with icons' },
  ],
  platformNotes: {
    web: 'Keyboard navigation follows the WAI-ARIA Authoring Practices.',
    ios: 'For app-level navigation prefer a native tab bar (expo-router Tabs).',
    android: 'Same as iOS. With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['navigation-bar', 'toggle-group'],
}

export const avatarMeta: ComponentMeta = {
  name: 'Avatar',
  slug: 'avatar',
  category: 'foundations',
  description: 'A profile image with an automatic initials fallback.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Avatar', 'getInitials'],
  keywords: ['profile', 'user', 'picture', 'image', 'initials'],
  parts: [
    {
      name: 'Avatar',
      props: [
        {
          name: 'src',
          type: 'string',
          description: 'Image URL. The fallback shows until it loads or if it fails.',
        },
        {
          name: 'alt',
          type: 'string',
          description: 'Accessible name — usually the person’s name.',
        },
        {
          name: 'fallback',
          type: 'string',
          description: 'Custom fallback text. Defaults to initials derived from `alt`.',
        },
        {
          name: 'size',
          type: "'xs' | 'sm' | 'md' | 'lg' | 'xl'",
          default: "'md'",
          description: '24–64px.',
        },
        {
          name: 'shape',
          type: "'circle' | 'square'",
          default: "'circle'",
          description: 'Outline shape.',
        },
      ],
    },
    {
      name: 'Avatar.Image / Avatar.Fallback',
      description: 'Compose manually for custom fallbacks.',
      props: [],
    },
  ],
  examples: [
    { name: 'basic', title: 'Image with fallback' },
    { name: 'sizes', title: 'Sizes' },
    { name: 'group', title: 'Stacked group' },
  ],
  playground: {
    component: 'Avatar',
    staticProps: { alt: 'Ada Lovelace' },
    controls: [
      { prop: 'size', type: 'select', options: ['xs', 'sm', 'md', 'lg', 'xl'], default: 'md' },
      { prop: 'shape', type: 'select', options: ['circle', 'square'], default: 'circle' },
    ],
  },
  platformNotes: {
    web: 'Uses a regular `<img>` with lazy decoding.',
    ios: 'Remote images are cached by React Native’s image loader.',
    android: 'Same as iOS; use HTTPS URLs.',
  },
  related: ['badge'],
}

export const sliderMeta: ComponentMeta = {
  name: 'Slider',
  slug: 'slider',
  category: 'forms',
  description: 'Pick a number, or a range, by dragging a thumb along a track.',
  status: 'beta',
  since: '0.2.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Slider'],
  keywords: ['range', 'volume', 'price', 'input range', 'track', 'thumb'],
  parts: [
    {
      name: 'Slider',
      props: [
        {
          name: 'value / defaultValue',
          type: 'number | number[]',
          description: 'A number for one thumb, or an array for a range.',
        },
        {
          name: 'onValueChange',
          type: '(value: number | number[]) => void',
          description: 'Called while the value changes, in the same shape you passed.',
        },
        {
          name: 'onValueCommit',
          type: '(value: number | number[]) => void',
          description: 'Called when a drag ends.',
        },
        { name: 'min', type: 'number', default: '0', description: 'Lowest value.' },
        { name: 'max', type: 'number', default: '100', description: 'Highest value.' },
        { name: 'step', type: 'number', default: '1', description: 'Increment.' },
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg'",
          default: "'md'",
          description: 'Thumb and track size.',
        },
        {
          name: 'orientation',
          type: "'horizontal' | 'vertical'",
          default: "'horizontal'",
          description: 'Direction of the track.',
        },
        { name: 'disabled', type: 'boolean', description: 'Prevent interaction.' },
        {
          name: 'aria-label / aria-labelledby',
          type: 'string',
          description: 'Accessible name. Required when there is no visible label.',
        },
        {
          name: 'getValueText',
          type: '(value: number) => string',
          description: 'Readable value for screen readers, e.g. a currency.',
        },
        {
          name: 'thumbLabels',
          type: 'string[]',
          description: 'Names for range thumbs. Default: “Minimum” / “Maximum”.',
        },
      ],
    },
  ],
  examples: [
    {
      name: 'basic',
      title: 'Single value',
      description: 'Controlled, with a visible label and value.',
    },
    { name: 'range', title: 'Range', description: 'Two thumbs with currency value text.' },
  ],
  playground: {
    component: 'Slider',
    staticProps: { 'aria-label': 'Playground slider', defaultValue: 40 },
    controls: [
      { prop: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md' },
      { prop: 'step', type: 'number', default: 1, min: 1, max: 25, step: 1 },
      { prop: 'disabled', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'Pointer, touch and keyboard input.',
    ios: 'Drag the thumb, or swipe up / down with VoiceOver.',
    android: 'Drag the thumb, or use TalkBack volume-key / swipe adjustments.',
  },
  related: ['input', 'progress', 'switch'],
}

export const radioGroupMeta: ComponentMeta = {
  name: 'Radio Group',
  slug: 'radio-group',
  category: 'forms',
  description: 'A set of mutually exclusive options where exactly one can be selected.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['RadioGroup'],
  keywords: ['radio', 'option', 'choice', 'single select'],
  parts: [
    {
      name: 'RadioGroup',
      props: [
        {
          name: 'value / defaultValue',
          type: 'string',
          description: 'Selected value (controlled / uncontrolled).',
        },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          description: 'Called when the selection changes.',
        },
        {
          name: 'orientation',
          type: "'vertical' | 'horizontal'",
          default: "'vertical'",
          description: 'Arrow-key direction and layout.',
        },
        { name: 'disabled', type: 'boolean', description: 'Disables all items.' },
        {
          name: 'name / required',
          type: 'string / boolean',
          description: 'Native form participation (web).',
        },
      ],
    },
    {
      name: 'RadioGroup.Item',
      props: [
        { name: 'value', type: 'string', required: true, description: 'The option value.' },
        { name: 'id', type: 'string', description: 'Link to a Label with the same `htmlFor`.' },
        { name: 'size', type: "'sm' | 'md'", default: "'md'", description: '16 or 20px.' },
        { name: 'disabled', type: 'boolean', description: 'Disables this item.' },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Plans' }],
  related: ['checkbox', 'select'],
}

export const passwordInputMeta: ComponentMeta = {
  name: 'Password Input',
  slug: 'password-input',
  category: 'forms',
  description: 'A password field with a button that shows and hides the text.',
  status: 'beta',
  since: '0.4.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['PasswordInput'],
  keywords: ['password', 'secret', 'show password', 'reveal', 'login'],
  parts: [
    {
      name: 'PasswordInput',
      description: 'Accepts every Input prop except `type` and `secureTextEntry`.',
      props: [
        {
          name: 'visible / defaultVisible',
          type: 'boolean',
          default: 'false',
          description: 'Whether the password is shown.',
        },
        {
          name: 'onVisibleChange',
          type: '(visible: boolean) => void',
          description: 'Called when the button is pressed.',
        },
        {
          name: 'toggleLabel',
          type: 'string',
          default: "'Show password'",
          description: 'Accessible name of the button.',
        },
        {
          name: 'autoComplete',
          type: 'string',
          default: "'current-password'",
          description: "Use 'new-password' on sign-up forms.",
        },
        { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'As Input.' },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Basic' }],
  platformNotes: {
    web: 'The field switches between `type="password"` and `type="text"`.',
    ios: 'Uses `secureTextEntry`; iOS may clear the field when typing resumes after hiding.',
    android: 'Uses `secureTextEntry`.',
  },
  related: ['input', 'form-field'],
}

export const numberInputMeta: ComponentMeta = {
  name: 'Number Input',
  slug: 'number-input',
  category: 'forms',
  description: 'A numeric field with − and + buttons, limits and a step.',
  status: 'beta',
  since: '0.4.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['NumberInput'],
  keywords: ['number', 'stepper', 'spinbutton', 'quantity', 'counter'],
  parts: [
    {
      name: 'NumberInput',
      description: 'Also accepts Input props such as `invalid`, `placeholder` and `aria-label`.',
      props: [
        {
          name: 'value / defaultValue',
          type: 'number | null',
          default: 'null',
          description: '`null` when the field is empty.',
        },
        {
          name: 'onValueChange',
          type: '(value: number | null) => void',
          description: 'Called when a valid number is typed or stepped.',
        },
        { name: 'min / max', type: 'number', description: 'Limits; typed values clamp on blur.' },
        {
          name: 'step',
          type: 'number',
          default: '1',
          description: 'Amount added by the buttons and arrow keys.',
        },
        {
          name: 'decrementLabel / incrementLabel',
          type: 'string',
          default: "'Decrease' / 'Increase'",
          description: 'Accessible names of the buttons.',
        },
        { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'As Input.' },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Basic' }, { name: 'decimal', title: 'Decimal step' }],
  platformNotes: {
    ios: 'VoiceOver swipe up / down steps the value (increment / decrement actions).',
    android: 'TalkBack volume keys or swipes step the value (increment / decrement actions).',
  },
  related: ['input', 'slider', 'form-field'],
}

export const progressMeta: ComponentMeta = {
  name: 'Progress',
  slug: 'progress',
  category: 'feedback',
  description: 'Shows how much of a task is complete.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Progress'],
  keywords: ['progress bar', 'upload', 'loading', 'percentage'],
  parts: [
    {
      name: 'Progress',
      props: [
        {
          name: 'value',
          type: 'number | null',
          description: 'Current value; `null` shows an indeterminate bar.',
        },
        { name: 'max', type: 'number', default: '100', description: 'Maximum value.' },
        { name: 'label', type: 'string', description: 'Accessible name.' },
        {
          name: 'tone',
          type: "'primary' | 'success' | 'warning' | 'error'",
          default: "'primary'",
          description: 'Indicator color.',
        },
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg'",
          default: "'md'",
          description: '4, 8 or 12px tall.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Animated upload' }],
  playground: {
    component: 'Progress',
    staticProps: { label: 'Upload progress' },
    controls: [
      { prop: 'value', type: 'number', default: 60, min: 0, max: 100, step: 5 },
      {
        prop: 'tone',
        type: 'select',
        options: ['primary', 'success', 'warning', 'error'],
        default: 'primary',
      },
      { prop: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md' },
    ],
  },
  related: ['circular-progress', 'spinner', 'skeleton'],
}

export const spinnerMeta: ComponentMeta = {
  name: 'Spinner',
  slug: 'spinner',
  category: 'feedback',
  description: 'An indeterminate loading indicator.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Spinner'],
  keywords: ['loading', 'busy', 'activity indicator'],
  parts: [
    {
      name: 'Spinner',
      props: [
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg'",
          default: "'md'",
          description: '16, 20 or 28px.',
        },
        {
          name: 'color',
          type: 'string',
          description: 'Theme token (e.g. `$primary`) or color. Defaults to the text color.',
        },
        { name: 'label', type: 'string', default: "'Loading'", description: 'Accessible name.' },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Sizes and colors' }],
  platformNotes: {
    web: 'Lightweight CSS-animated SVG (no JS animation).',
    ios: 'Native `ActivityIndicator`.',
    android: 'Native `ActivityIndicator`.',
  },
  related: ['progress', 'skeleton', 'button'],
}

export const skeletonMeta: ComponentMeta = {
  name: 'Skeleton',
  slug: 'skeleton',
  category: 'foundations',
  description: 'A pulsing placeholder that previews the shape of loading content.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Skeleton'],
  keywords: ['loading', 'placeholder', 'shimmer'],
  parts: [
    {
      name: 'Skeleton',
      description: 'Accepts any layout/size style prop.',
      props: [
        {
          name: 'circle',
          type: 'boolean',
          default: 'false',
          description: 'Fully rounded (for avatars).',
        },
      ],
    },
  ],
  examples: [{ name: 'card', title: 'Loading card' }],
  platformNotes: {
    web: 'Pulses with a CSS animation.',
    ios: 'Static placeholder (no animation).',
    android: 'Static placeholder (no animation).',
  },
  related: ['spinner', 'progress'],
}

export const alertMeta: ComponentMeta = {
  name: 'Alert',
  slug: 'alert',
  category: 'feedback',
  description: 'An inline message that draws attention without interrupting the task.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Alert'],
  keywords: ['callout', 'banner', 'notice', 'message', 'warning', 'error'],
  parts: [
    {
      name: 'Alert',
      props: [
        {
          name: 'variant',
          type: "'default' | 'info' | 'success' | 'warning' | 'error'",
          default: "'default'",
          description: 'Intent and icon.',
        },
        {
          name: 'icon',
          type: 'ReactNode | null',
          description: 'Custom icon, or `null` to hide it.',
        },
      ],
    },
    { name: 'Alert.Title', props: [] },
    { name: 'Alert.Description', props: [] },
  ],
  examples: [{ name: 'variants', title: 'Variants' }],
  related: ['toast', 'badge'],
}

export const emptyStateMeta: ComponentMeta = {
  name: 'Empty State',
  slug: 'empty-state',
  category: 'feedback',
  description: 'A placeholder for an empty list, search or page, with the action that fills it.',
  status: 'beta',
  since: '0.4.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['EmptyState'],
  keywords: ['empty', 'no results', 'blank slate', 'zero state', 'placeholder'],
  parts: [
    {
      name: 'EmptyState',
      props: [
        { name: 'title', type: 'ReactNode', description: 'Short heading.' },
        { name: 'description', type: 'ReactNode', description: 'One or two sentences.' },
        { name: 'icon', type: 'ReactNode', description: 'Icon in a circle above the title.' },
        { name: 'children', type: 'ReactNode', description: 'Actions, usually Buttons.' },
        {
          name: 'headingLevel',
          type: '1 | 2 | 3 | 4 | 5 | 6',
          default: '3',
          description: 'Heading level of the title.',
        },
        {
          name: 'bordered',
          type: 'boolean',
          default: 'false',
          description: 'Dashed border, for empty areas inside a page.',
        },
        {
          name: 'tone',
          type: "'default' | 'error'",
          default: "'default'",
          description: 'Colors of the icon circle.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Basic' }, { name: 'search', title: 'No search results' }],
  platformNotes: {},
  related: ['error-state', 'skeleton', 'alert'],
}

export const searchMeta: ComponentMeta = {
  name: 'Search',
  slug: 'search',
  category: 'advanced',
  description: 'A search field with a magnifier, a clear button and a loading state.',
  status: 'beta',
  since: '0.6.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Search', 'SearchProps'],
  keywords: ['search', 'find', 'filter', 'query', 'searchbox', 'lookup'],
  parts: [
    {
      name: 'Search',
      description: 'Also takes the Input props (`placeholder`, `disabled`, `id`…).',
      props: [
        {
          name: 'value / defaultValue / onValueChange',
          type: 'string',
          description: 'The text (controlled or not). Filter live from `onValueChange`.',
        },
        {
          name: 'onSearch',
          type: '(value: string) => void',
          description: 'Enter, or the keyboard’s search key, was pressed.',
        },
        {
          name: 'loading',
          type: 'boolean',
          default: 'false',
          description: 'A spinner replaces the magnifier; sets `aria-busy`.',
        },
        { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Height.' },
        {
          name: 'aria-label',
          type: 'string',
          default: "'Search'",
          description: 'Name of the field. Say what it searches.',
        },
        {
          name: 'clearLabel',
          type: 'string',
          default: "'Clear search'",
          description: 'Name of the clear button.',
        },
        {
          name: 'landmark',
          type: 'boolean',
          default: 'false',
          description: 'Wraps it in a `search` landmark (web) for the page’s main search.',
        },
      ],
    },
  ],
  examples: [
    { name: 'basic', title: 'Search on Enter' },
    {
      name: 'live',
      title: 'Live results',
      description: 'Filters as you type, with the loading spinner and a live result count.',
    },
  ],
  playground: {
    component: 'Search',
    controls: [
      { prop: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md' },
      { prop: 'loading', type: 'boolean', default: false },
      { prop: 'placeholder', type: 'text', default: 'Search' },
      { prop: 'disabled', type: 'boolean', default: false },
    ],
  },
  platformNotes: {
    web: 'The Enter key hint is "search" on phone keyboards.',
    ios: 'The keyboard’s return key reads "Search".',
    android: 'Same as iOS.',
  },
  related: ['input', 'command-palette', 'autocomplete', 'data-table'],
}

export const chipMeta: ComponentMeta = {
  name: 'Chip',
  slug: 'chip',
  category: 'data-display',
  description: 'A compact element for a filter, an entered value such as a recipient, or a suggested action.',
  status: 'beta',
  since: '0.2.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['Chip'],
  keywords: ['tag', 'filter', 'pill', 'token', 'material', 'input chip', 'suggestion'],
  parts: [
    {
      name: 'Chip',
      props: [
        { name: 'children', type: 'ReactNode', required: true, description: 'The label.' },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon or avatar.' },
        {
          name: 'selected / defaultSelected',
          type: 'boolean',
          description: 'Makes it a filter chip that turns on and off; shows a check when on.',
        },
        {
          name: 'onSelectedChange',
          type: '(selected: boolean) => void',
          description: 'Called when a filter chip is turned on or off.',
        },
        {
          name: 'onRemove',
          type: '() => void',
          description: 'Makes it an input chip with a remove (×) button.',
        },
        {
          name: 'removeLabel',
          type: 'string',
          default: '“Remove {children}”',
          description: 'Accessible name of the remove button.',
        },
        { name: 'onPress', type: '() => void', description: 'Makes it an action (assist) chip.' },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Not interactive.' },
      ],
    },
  ],
  examples: [
    { name: 'filter', title: 'Filter chips' },
    {
      name: 'input',
      title: 'Input and action chips',
      description: 'Removable recipients, and suggested actions.',
    },
  ],
  platformNotes: {
    web: 'Pressable chips are native `<button>` elements.',
    ios: 'Touch targets are extended to 44pt with hit slop.',
    android: 'Filter chips are announced as toggle buttons. With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['badge', 'toggle-group', 'button'],
}

export const listMeta: ComponentMeta = {
  name: 'List',
  slug: 'list',
  category: 'data-display',
  description: 'A vertical list of rows with a leading visual, text and trailing meta.',
  status: 'beta',
  since: '0.6.0',
  platforms: ['web', 'ios', 'android'],
  exports: [
    'List',
    'ListFrame',
    'ListItemFrame',
    'ListItemTitle',
    'ListItemDescription',
    'ListProps',
    'ListItemProps',
  ],
  keywords: ['list', 'rows', 'items', 'menu list', 'settings', 'contacts', 'list item'],
  parts: [
    {
      name: 'List',
      props: [
        {
          name: 'variant',
          type: "'plain' | 'outline'",
          default: "'plain'",
          description: '`outline` puts the rows on a bordered card surface.',
        },
        {
          name: 'size',
          type: "'sm' | 'md'",
          default: "'md'",
          description: 'Row padding and text size.',
        },
        {
          name: 'divided',
          type: 'boolean',
          default: 'false',
          description: 'Draws a line between items.',
        },
      ],
    },
    {
      name: 'List.Item',
      props: [
        { name: 'title', type: 'ReactNode', description: 'Main line.' },
        { name: 'description', type: 'ReactNode', description: 'Muted second line.' },
        {
          name: 'leading',
          type: 'ReactNode',
          description: 'Icon, Avatar or image before the text. Icons are 20px and muted.',
        },
        {
          name: 'trailing',
          type: 'ReactNode',
          description: 'Meta text, a Badge, a chevron, or actions (only when the item has no `onPress`).',
        },
        {
          name: 'onPress',
          type: '(event) => void',
          description: 'Makes the whole row one button.',
        },
        { name: 'disabled', type: 'boolean', default: 'false', description: 'Blocks `onPress`.' },
        {
          name: 'children',
          type: 'ReactNode',
          description: 'Custom content in place of `title` and `description`.',
        },
      ],
    },
    {
      name: 'List.ItemTitle / List.ItemDescription',
      description: 'The styled text, for custom `children`.',
      props: [],
    },
  ],
  examples: [
    { name: 'basic', title: 'Basic' },
    {
      name: 'interactive',
      title: 'Pressable rows',
      description: 'Each row is one button; the last one is disabled.',
    },
    {
      name: 'with-avatars',
      title: 'Avatars and actions',
      description: 'Rows without `onPress` can hold their own buttons.',
    },
  ],
  playground: {
    component: 'List',
    controls: [
      { prop: 'variant', type: 'select', options: ['plain', 'outline'], default: 'outline' },
      { prop: 'size', type: 'select', options: ['sm', 'md'], default: 'md' },
      { prop: 'divided', type: 'boolean', default: true },
    ],
  },
  platformNotes: {
    web: 'A pressable row is a `<button>` inside the list item.',
    ios: 'A pressable row is one accessible button; VoiceOver reads all of its text.',
    android: 'Same as iOS. Pressable rows show the ripple when the config has `androidRipple`.',
  },
  related: ['card', 'avatar', 'badge', 'separator'],
}

export const paginationMeta: ComponentMeta = {
  name: 'Pagination',
  slug: 'pagination',
  category: 'navigation',
  description: 'Previous and next buttons around the page numbers of a long list or table.',
  status: 'beta',
  since: '0.6.0',
  platforms: ['web', 'ios', 'android'],
  exports: [
    'Pagination',
    'getPaginationItems',
    'PaginationProps',
    'PaginationItem',
    'PaginationLabels',
  ],
  keywords: ['pagination', 'pager', 'pages', 'next', 'previous', 'paging'],
  parts: [
    {
      name: 'Pagination',
      props: [
        { name: 'count', type: 'number', required: true, description: 'Number of pages.' },
        { name: 'page', type: 'number', description: 'Current page, from 1 (controlled).' },
        {
          name: 'defaultPage',
          type: 'number',
          default: '1',
          description: 'Initial page when uncontrolled.',
        },
        { name: 'onPageChange', type: '(page: number) => void', description: 'Page changed.' },
        {
          name: 'siblings',
          type: 'number',
          default: '1',
          description: 'Pages shown on each side of the current one.',
        },
        {
          name: 'boundaries',
          type: 'number',
          default: '1',
          description: 'Pages always shown at the start and the end.',
        },
        {
          name: 'variant',
          type: "'full' | 'compact'",
          default: "'full'",
          description: '`compact` shows "Page 3 of 10" instead of numbers; good on phones.',
        },
        { name: 'size', type: "'sm' | 'md'", default: "'md'", description: 'Button size.' },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Disables every button.',
        },
        {
          name: 'labels',
          type: 'Partial<PaginationLabels>',
          description: 'Button names and the compact text, for translation.',
        },
      ],
    },
    {
      name: 'getPaginationItems(page, count, options?)',
      description: 'The page numbers and gaps to show, for building your own pager. The item count stays the same while paging.',
      props: [],
    },
  ],
  examples: [
    { name: 'basic', title: 'Basic' },
    { name: 'controlled', title: 'Controlled', description: 'Drive it from your data’s page.' },
    { name: 'compact', title: 'Compact' },
  ],
  playground: {
    component: 'Pagination',
    staticProps: { count: 10 },
    controls: [
      { prop: 'variant', type: 'select', options: ['full', 'compact'], default: 'full' },
      { prop: 'size', type: 'select', options: ['sm', 'md'], default: 'md' },
      { prop: 'siblings', type: 'number', default: 1, min: 0, max: 3 },
      { prop: 'disabled', type: 'boolean', default: false },
    ],
  },
  related: ['table', 'button'],
}

export const alertDialogMeta: ComponentMeta = {
  name: 'Alert Dialog',
  slug: 'alert-dialog',
  category: 'feedback',
  description: 'Interrupts the user to confirm an important or destructive action before it happens.',
  status: 'beta',
  since: '0.2.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['AlertDialog'],
  keywords: ['confirm', 'confirmation', 'modal', 'destructive', 'delete', 'warning'],
  parts: [
    {
      name: 'AlertDialog',
      props: [
        { name: 'open / defaultOpen', type: 'boolean', description: 'Open state.' },
        {
          name: 'onOpenChange',
          type: '(open: boolean) => void',
          description: 'Called when the dialog opens or closes.',
        },
      ],
    },
    {
      name: 'AlertDialog.Trigger',
      description: 'Opens the dialog. Use `asChild` to render your Button.',
      props: [],
    },
    {
      name: 'AlertDialog.Content',
      props: [
        {
          name: 'size',
          type: "'sm' | 'md' | 'lg' | 'xl'",
          default: "'sm'",
          description: 'Max width.',
        },
      ],
    },
    {
      name: 'AlertDialog.Title',
      props: [
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          description: 'The question, e.g. “Delete this project?”. Names the dialog.',
        },
      ],
    },
    {
      name: 'AlertDialog.Description',
      props: [
        {
          name: 'children',
          type: 'ReactNode',
          required: true,
          description: 'The consequences. Announced with the title.',
        },
      ],
    },
    {
      name: 'AlertDialog.Cancel',
      description: 'Closes without acting. Receives focus when the dialog opens.',
      props: [{ name: 'asChild', type: 'boolean', description: 'Wrap your own Button.' }],
    },
    {
      name: 'AlertDialog.Action',
      description: 'Confirms and closes. For work that takes time, use a plain Button and close when it finishes.',
      props: [{ name: 'asChild', type: 'boolean', description: 'Wrap your own Button.' }],
    },
    { name: 'AlertDialog.Header / Footer', props: [] },
  ],
  examples: [
    { name: 'basic', title: 'Destructive confirmation' },
    {
      name: 'async',
      title: 'Waits for the action',
      description: 'Stays open and busy until the request finishes.',
    },
  ],
  platformNotes: {
    web: 'Rendered in a portal with the page scroll locked.',
    ios: 'Rendered in a native portal above navigation.',
    android: 'The back button cancels, like Escape.',
  },
  related: ['dialog', 'sheet', 'toast'],
}

export const toastMeta: ComponentMeta = {
  name: 'Toast',
  slug: 'toast',
  category: 'feedback',
  description: 'Brief, non-blocking notifications triggered imperatively with `toast()`.',
  status: 'beta',
  since: '0.1.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['toast', 'Toaster'],
  keywords: ['notification', 'snackbar', 'message', 'sonner'],
  parts: [
    {
      name: 'toast(title, options?)',
      description: 'Also `toast.success / error / warning / info / loading / promise / dismiss`.',
      props: [
        { name: 'description', type: 'ReactNode', description: 'Secondary text.' },
        {
          name: 'duration',
          type: 'number',
          default: '4000',
          description: 'Milliseconds before auto-dismiss.',
        },
        {
          name: 'action',
          type: '{ label: string; onClick: () => void }',
          description: 'Inline action button (e.g. Undo).',
        },
        {
          name: 'dismissible',
          type: 'boolean',
          default: 'true',
          description: 'Shows the close button and allows swipe.',
        },
      ],
    },
    {
      name: 'Toaster',
      description: 'Rendered automatically by UniversalProvider; configure with its `toaster` prop.',
      props: [
        {
          name: 'position',
          type: "'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right'",
          default: "'bottom-right'",
          description: 'Screen corner.',
        },
        { name: 'duration', type: 'number', default: '4000', description: 'Default duration.' },
        {
          name: 'visibleToasts',
          type: 'number',
          default: '4',
          description: 'Maximum stacked toasts.',
        },
      ],
    },
  ],
  examples: [{ name: 'types', title: 'Types' }, { name: 'action', title: 'With action' }],
  platformNotes: {
    web: 'Stacked in the chosen corner; hover expands the stack.',
    ios: 'Rendered in-app with swipe-to-dismiss.',
    android: 'Rendered in-app with swipe-to-dismiss. With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['alert', 'snackbar'],
}

export const tooltipMeta: ComponentMeta = {
  name: 'Tooltip',
  slug: 'tooltip',
  category: 'overlay',
  description: 'A short hint shown when an element is hovered or focused.',
  status: 'stable',
  since: '0.1.0',
  platforms: ['web'],
  exports: ['Tooltip'],
  keywords: ['hint', 'popover', 'title', 'help'],
  parts: [
    {
      name: 'Tooltip',
      props: [
        {
          name: 'content',
          type: 'ReactNode',
          required: true,
          description: 'The hint. Keep it short.',
        },
        {
          name: 'side',
          type: "'top' | 'right' | 'bottom' | 'left'",
          default: "'top'",
          description: 'Preferred placement (flips to fit).',
        },
        { name: 'delay', type: 'number', default: '300', description: 'Hover delay in ms.' },
        {
          name: 'disabled',
          type: 'boolean',
          default: 'false',
          description: 'Render only the trigger.',
        },
        {
          name: 'open / defaultOpen / onOpenChange',
          type: 'boolean / boolean / fn',
          description: 'Control visibility.',
        },
      ],
    },
  ],
  examples: [{ name: 'basic', title: 'Toolbar' }],
  platformNotes: {
    web: 'Positioned with Floating UI; flips and shifts to stay on screen.',
    ios: 'Not rendered — touch has no hover. Only the trigger is shown.',
    android: 'Not rendered — use a visible label or long-press hint instead.',
  },
  related: ['icon-button', 'popover', 'hover-card'],
}

export const dropdownMenuMeta: ComponentMeta = {
  name: 'Dropdown Menu',
  slug: 'dropdown-menu',
  category: 'navigation',
  description: 'A list of actions or options that opens from a button.',
  status: 'beta',
  since: '0.2.0',
  platforms: ['web', 'ios', 'android'],
  exports: ['DropdownMenu'],
  keywords: ['menu', 'actions', 'more', 'overflow', 'kebab', 'context', 'options'],
  parts: [
    {
      name: 'DropdownMenu',
      props: [
        { name: 'open / defaultOpen', type: 'boolean', description: 'Open state.' },
        {
          name: 'onOpenChange',
          type: '(open: boolean) => void',
          description: 'Called when the menu opens or closes.',
        },
        {
          name: 'side',
          type: "'top' | 'right' | 'bottom' | 'left'",
          default: "'bottom'",
          description: 'Where to open relative to the trigger (web).',
        },
        {
          name: 'align',
          type: "'start' | 'center' | 'end'",
          default: "'start'",
          description: 'Alignment along that side (web).',
        },
      ],
    },
    {
      name: 'DropdownMenu.Trigger',
      props: [
        {
          name: 'children',
          type: 'ReactElement',
          required: true,
          description: 'One element, usually a Button or IconButton.',
        },
      ],
    },
    {
      name: 'DropdownMenu.Content',
      props: [
        {
          name: 'minWidth',
          type: "'$40' | '$48' | '$56' | '$64'",
          default: "'$48'",
          description: 'Minimum menu width (web).',
        },
      ],
    },
    {
      name: 'DropdownMenu.Item',
      props: [
        {
          name: 'onSelect',
          type: '() => void',
          description: 'Called when chosen; the menu closes.',
        },
        { name: 'icon', type: 'ReactNode', description: 'Leading icon.' },
        { name: 'shortcut', type: 'string', description: 'Keyboard hint on the right (web).' },
        { name: 'destructive', type: 'boolean', description: 'Style as a dangerous action.' },
        { name: 'disabled', type: 'boolean', description: 'Skip this item.' },
        {
          name: 'textValue',
          type: 'string',
          description: 'Type-ahead text when children is not a string.',
        },
      ],
    },
    {
      name: 'DropdownMenu.CheckboxItem',
      props: [
        { name: 'checked', type: 'boolean', description: 'Checked state.' },
        {
          name: 'onCheckedChange',
          type: '(checked: boolean) => void',
          description: 'Called with the new state.',
        },
      ],
    },
    {
      name: 'DropdownMenu.RadioGroup',
      props: [
        { name: 'value', type: 'string', description: 'Selected item.' },
        {
          name: 'onValueChange',
          type: '(value: string) => void',
          description: 'Called with the chosen value.',
        },
      ],
    },
    {
      name: 'DropdownMenu.RadioItem',
      props: [{ name: 'value', type: 'string', required: true, description: 'Item value.' }],
    },
    {
      name: 'DropdownMenu.Label / Separator / Group',
      props: [
        { name: 'children', type: 'ReactNode', description: 'Section heading and grouping.' },
      ],
    },
  ],
  examples: [
    {
      name: 'basic',
      title: 'Account menu',
      description: 'Icons, shortcuts, a disabled and a destructive item.',
    },
    {
      name: 'options',
      title: 'Checkbox and radio items',
      description: 'View settings from an icon button.',
    },
  ],
  platformNotes: {
    web: 'Floating menu next to the trigger with full keyboard support.',
    ios: 'Opens as a bottom sheet of large rows (native menus need a native module that Expo Go does not include). Shortcut hints are hidden.',
    android: 'Same as iOS; the back gesture closes the sheet. With `androidRipple` (on in `material()`), presses show the native ripple.',
  },
  related: ['popover', 'select', 'context-menu'],
}
